# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('abbrv', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('conf_game', models.IntegerField(blank=True, null=True)),
                ('home_id', models.IntegerField(blank=True, null=True)),
                ('away_id', models.IntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameLine',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('player_id', models.TextField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('opponent_id', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('fg_made', models.IntegerField(blank=True, null=True)),
                ('fg_attempt', models.IntegerField(blank=True, null=True)),
                ('two_made', models.IntegerField(blank=True, null=True)),
                ('two_attempt', models.IntegerField(blank=True, null=True)),
                ('three_made', models.IntegerField(blank=True, null=True)),
                ('three_attempt', models.IntegerField(blank=True, null=True)),
                ('ft_made', models.IntegerField(blank=True, null=True)),
                ('ft_attempt', models.IntegerField(blank=True, null=True)),
                ('orb', models.IntegerField(blank=True, null=True)),
                ('drb', models.IntegerField(blank=True, null=True)),
                ('trb', models.IntegerField(blank=True, null=True)),
                ('ast', models.IntegerField(blank=True, null=True)),
                ('stl', models.IntegerField(blank=True, null=True)),
                ('blk', models.IntegerField(blank=True, null=True)),
                ('tov', models.IntegerField(blank=True, null=True)),
                ('pf', models.IntegerField(blank=True, null=True)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('coolness', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('conference', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('conf_wins', models.IntegerField(blank=True, null=True)),
                ('conf_losses', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
    ]
